services:
  puppeteer-render:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app/pics
    command: ["node", "server.js", "debug"]